### ISSUE TITLE
Error on latest macOS

### ISSUE THREAD

**Issue by lackhole** [mukunku/tag-exists-action#11]
<img width="1094" alt="image" src="https://github.com/mukunku/tag-exists-action/assets/35574936/83a7cbfd-b43a-4416-a648-ccfcff443ca1">

When I run your workflow on self-hosted latest macOS, an error occurs.
Then I found this answer in SO: https://stackoverflow.com/a/69878863/8176989

How can I fix it?

**Comment by mukunku** [comment]
@lackhole Can you try the latest `v.1.3.0` release and see if that fixes the issue for you?

https://github.com/marketplace/actions/tag-exists-action

**Comment by mukunku** [comment]
I confirmed v1.3.0 works on the `latest-macos`. Closing out this ticket but feel free to re-open if the issue continues.
