### ISSUE TITLE
v1.3.0 errored

### ISSUE THREAD

**Issue by tinect** [mukunku/tag-exists-action#15]
Hey,

after upgrading from 1.2.0 to 1.3.0 we are stuck with the following error message.
Is there any task missing?

> Download action repository 'mukunku/tag-exists-action@v1.3.0' (SHA:dec555f9852d16348164eef27bdaf4da9f1a3ea0)
> Error: Could not find file '/home/runner/work/_actions/_temp_9eabd213-85b7-451f-a88e-6470684c15d7/_staging/mukunku-tag-exists-action-dec555f/node_modules/.bin/uuid'.

**Comment by mukunku** [comment]
That's strange, the file is [available here](https://github.com/mukunku/tag-exists-action/blob/master/node_modules/.bin/uuid). What OS are you running the workflow on? Any chance you could share a link to your repo if it's public?

**Comment by mukunku** [comment]
Looks like it's a windows issue: https://github.com/mukunku/tag-exists-action/pull/16

I'll see if I can get a fix into v1.3.0

This is my bad for not having good test coverage 😔

**Comment by mukunku** [comment]
I pushed a fix to `v1.3.0` directly. Let me know if that fixes it for you.

I didn't want to push a new version since i just released 1.3.0.

**Comment by tinect** [comment]
It is ubuntu-latest.

It looks good by now:
https://github.com/FriendsOfShopware/FroshPlatformMailArchive/actions/runs/5849465306/job/15857822103

errored one was:
https://github.com/FriendsOfShopware/FroshPlatformMailArchive/actions/runs/5841498833

**Comment by mukunku** [comment]
I'm glad the change fixed the issue for you. Thanks for reporting it 🍺
