### ISSUE TITLE
Always return 'false'

### ISSUE THREAD

**Issue by opensourcer2** [mukunku/tag-exists-action#28]
For a repo in an organization like this [one](https://github.com/pubinary/coppeliasim/tags), searching for tags always return `false` even when the tag actually exists.

**Comment by mukunku** [comment]
I tested it in this PR and it works fine: https://github.com/mukunku/tag-exists-action/pull/29

![{31F65B75-E361-4A0A-8F32-74C043758BB0}](https://github.com/user-attachments/assets/00a24629-44e0-4a59-b8f7-947daf017ba6)

Going to close this out but feel free to re-open if I missed something.

**Comment by opensourcer2** [comment]
Thanks. I will investigate more. This is odd.

**Comment by opensourcer2** [comment]
I found the problem. A trailing newline character in my code is breaking things :man_facepalming: Thanks for this project.
