### ISSUE TITLE
Please convert output with latest environment files

### ISSUE THREAD

**Issue by rsharma02-entrata** [mukunku/tag-exists-action#4]
Please check this- 
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

**Comment by edlerd** [comment]
I think it refers to a warning, that set-output is deprecated. But this is only true, while inside a workflow yaml file. But in an action, it is actually fine to still use `core.setOutput`. Updating to the latest `@actions/core` version should fix it.

I found the same problem and the possible solution here: https://github.com/actions/toolkit/issues/1218

**Comment by mukunku** [comment]
Thanks @edlerd . I bumped the @actions/core version to 1.10 and the warning went away. I updated the v1.1.0 release instead of publishing a new one.

**Comment by pmalek** [comment]
Hi @mukunku 👋 

Isn't this still using `@actions/core` 1.9.1? As per:

- https://github.com/mukunku/tag-exists-action/blob/v1.2.0/package-lock.json#L12
- and https://github.com/mukunku/tag-exists-action/blob/v1.2.0/package.json#L21 

?

**Comment by mukunku** [comment]
> Hi @mukunku 👋
> 
> Isn't this still using `@actions/core` 1.9.1? As per:
> 
>     * https://github.com/mukunku/tag-exists-action/blob/v1.2.0/package-lock.json#L12
> 
>     * and https://github.com/mukunku/tag-exists-action/blob/v1.2.0/package.json#L21
> 
> 
> ?

I believe `^1.9.1` should still resolve to `1.10.0` . Not sure why npm didn't update the package.json to make `1.10.0` the minimum though.

I'm basing this on [this article](https://michaelsoolee.com/npm-package-tilde-caret/):

> If you see ^1.0.2 it means to install version 1.0.2 or the latest minor or patch version such as 1.1.0.

**Comment by KevinRohn** [comment]
Please check the open PR.

It`s still not resolved.

I fixed it in this commit:
https://github.com/mukunku/tag-exists-action/pull/9/commits/3e6a721396cba9185eeda60afe8f2feaadc99651

**Comment by kevinbutto** [comment]
@mukunku thank you for this action! 
any update on this though? I'm still getting the "`set-output` command is deprecated " warning
