### ISSUE TITLE
Please release v1.1.0 to marketplace

### ISSUE THREAD

**Issue by edlerd** [mukunku/tag-exists-action#5]
Thank you for merging [this](https://github.com/mukunku/tag-exists-action/pull/3) :)
I tried to use it immediately, and the new version 1.1.0 from the README is not found to be run yet. I assume it needs publishing to the marketplace. Could you look into that, please?

(Repeating my message from the PR here, because it might have gone lost over there, as the PR was already closed)

**Comment by mukunku** [comment]
Thanks for opening the PR.

I didn't release it yesterday because I wasn't going to be able to test it to confirm. I released it now, can you let me know if it's working for you? 🙂

**Comment by edlerd** [comment]
Works like a charm, and deprecation warnings are gone. Thanks again :)
